// Code generated by protoc-gen-go.
// source: DataBurst.proto
// DO NOT EDIT!

package dataframe

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type DataBurst struct {
	Frames           []*DataFrame `protobuf:"bytes,1,rep,name=frames" json:"frames,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *DataBurst) Reset()         { *m = DataBurst{} }
func (m *DataBurst) String() string { return proto.CompactTextString(m) }
func (*DataBurst) ProtoMessage()    {}

func (m *DataBurst) GetFrames() []*DataFrame {
	if m != nil {
		return m.Frames
	}
	return nil
}

func init() {
}
