// Code generated by protoc-gen-go.
// source: RequestMulti.proto
// DO NOT EDIT!

package dataframe

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type RequestMulti struct {
	Requests         []*RequestSource `protobuf:"bytes,1,rep,name=requests" json:"requests,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *RequestMulti) Reset()         { *m = RequestMulti{} }
func (m *RequestMulti) String() string { return proto.CompactTextString(m) }
func (*RequestMulti) ProtoMessage()    {}

func (m *RequestMulti) GetRequests() []*RequestSource {
	if m != nil {
		return m.Requests
	}
	return nil
}

type RequestSource struct {
	Source           []*RequestSource_Tag `protobuf:"bytes,1,rep,name=source" json:"source,omitempty"`
	Alpha            *uint64              `protobuf:"fixed64,2,req,name=alpha" json:"alpha,omitempty"`
	Omega            *uint64              `protobuf:"fixed64,3,req,name=omega" json:"omega,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *RequestSource) Reset()         { *m = RequestSource{} }
func (m *RequestSource) String() string { return proto.CompactTextString(m) }
func (*RequestSource) ProtoMessage()    {}

func (m *RequestSource) GetSource() []*RequestSource_Tag {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *RequestSource) GetAlpha() uint64 {
	if m != nil && m.Alpha != nil {
		return *m.Alpha
	}
	return 0
}

func (m *RequestSource) GetOmega() uint64 {
	if m != nil && m.Omega != nil {
		return *m.Omega
	}
	return 0
}

type RequestSource_Tag struct {
	Field            *string `protobuf:"bytes,1,req,name=field" json:"field,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestSource_Tag) Reset()         { *m = RequestSource_Tag{} }
func (m *RequestSource_Tag) String() string { return proto.CompactTextString(m) }
func (*RequestSource_Tag) ProtoMessage()    {}

func (m *RequestSource_Tag) GetField() string {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return ""
}

func (m *RequestSource_Tag) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
}
